server:
  port: 4200
  servlet:
    context-path: /hello-im/api

spring:
  datasource:
    url: jdbc:mysql://120.79.155.125:4001/hello_im?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapping/**/*.xml

im-sys:
  error-code:
    token-expiration: 0001
    token-invalidation: 0002
    token-missing: 0003
    bad-request: 0004
    empty-parameter: 0005
    enum-not-found: 0006
    sing-in-error: 0007
    system-error: 0008