server:
  port: 4200
  servlet:
    context-path: /hello-im/api

spring:
  datasource:
    url: jdbc:mysql://120.79.155.125:4001/hello_im?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.github.mrag.helloim: debug

mybatis:
  mapper-locations: classpath:/mapping/**/*.xml
  configuration:
    default-enum-type-handler: com.github.mrag.helloim.common.enums.EnumsTypeHandler

system:
  properties:
    errors:
      token-expiration: 0001
      token-missing: 0002
      token-invalidation: 0003
      bad-request: 0004
      login-fail: 0005
      internal-server-error: 0006
      enum-not-found: 0007
