GET http://localhost:5000/api/student/list

###

POST http://localhost:5000/api/student/save
Content-Type: application/json

{
  "status": "学业进行中"
}

###

GET http://localhost:5000/api/academy/list

###

GET http://localhost:5000/api/selection/itemList

###