server:
  port: 5000
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://120.79.155.125:4001/student_system?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 600000 # 毫秒
      minimum-idle: 3 # 最小连接数，保障库中始终有这么几条连接
      connection-test-query: select 1
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    default-enum-type-handler: com.example.studentsystem.common.Enums.EnumsTypeHandler
logging:
  level:
    com.example.studentsystem: debug
pagehelper:
  helper-dialect: mysql
